<?php
return array (
  'DB_TYPE' => 'mysql',
  'DB_HOST' => '127.0.0.1',
  'DB_NAME' => 'getqq',
  'DB_USER' => 'root',
  'DB_PWD' => '',
  'DB_PORT' => '3306',
  'DB_PREFIX' => 'tj_',
  'TMPL_ACTION_ERROR' => './view/msg.html',
  'TMPL_ACTION_SUCCESS' => './view/msg.html',
  'cfg_sitetitle' => '石家庄新华电脑学校',
  'cfg_seotitle' => '石家庄新华电脑学校',
  'cfg_keyword' => '石家庄新华电脑学校',
  'cfg_desc' => '石家庄新华电脑学校',
  'cfg_regstatus' => '1',
  'cfg_isvip' => '1',
  'cfg_viptime' => '3',
  'cfg_close' => '1',
  'cfg_closemsg' => '网站启开',
  'cfg_mailauto' => '0',
  'cfg_vipmprice' => '10',
  'cfg_vipyprice' => '20',
  'cfg_sitenum' => '10',
  'cfg_emailnum' => '100',
  'cfg_emailtplnum' => '100',
  'cfg_islogin' => '1',
  'cfg_api' => 'paipai',
);
?>